### ISSUE TITLE
Regexp optimization

### ISSUE THREAD

**Issue by ramizpolic** [bank-vaults/secret-init#88]
just realized that the new regexp Vault matcher could have a high time complexity. this could be problematic when there are a lot of secrets to inject. let's analyze it and decide to keep or switch

**Comment by csatib02** [comment]
In the `injector` side of the secret injection procedure there is a regex that checks whether the passed reference is a vault path: https://github.com/bank-vaults/internal/blob/60567c97627f3ff44b759a23246f21e5beaf2eef/injector/injector.go#L72

**Comment by ramizpolic** [comment]
Should be okay
